### ISSUE TITLE
PHP Warning 'yii\base\ErrorException' with message 'array_rand(): Array is empty'

### ISSUE THREAD

**Issue by belkin** [studioespresso/craft3-seeder#11]
I'm getting the following error on some sections (which is strange) but I can't understand on which field (if it's field) can't go further.

```PHP Warning 'yii\base\ErrorException' with message 'array_rand(): Array is empty'

in vendor/studioespresso/craft-seeder/src/services/fields/Fields.php:119

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'array_rand(): A...', '/Users/belkinfa...', 119, Array)
#1 vendor/studioespresso/craft-seeder/src/services/fields/Fields.php(119): array_rand(Array)
#2 vendor/studioespresso/craft-seeder/src/services/SeederService.php(50): studioespresso\seeder\services\fields\Fields->Categories(Object(craft\fields\Categories), Object(craft\elements\Entry))
#3 vendor/studioespresso/craft-seeder/src/services/Entries.php(81): studioespresso\seeder\services\SeederService->populateFields(Array, Object(craft\elements\Entry))
#4 vendor/studioespresso/craft-seeder/src/console/controllers/GenerateController.php(80): studioespresso\seeder\services\Entries->generate(Object(craft\models\Section), 12)
#5 [internal function]: studioespresso\seeder\console\controllers\GenerateController->actionEntries()
#6 vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('entries', Array)
#9 vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('entries', Array)
#10 vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('seeder/generate...', Array)
#11 vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('seeder/generate...', Array)
#12 /vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('seeder/generate...', Array)
#13 /vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#14 craft(22): yii\base\Application->run()
#15 {main}
```
PHP version: 7.1.22 (tried with 7.2.10 same situation)
Craft version: 3.1.19
Seeder version: 3.0.1
Fields: SuperTable fields, Redactor, Date, Plain text, Category, Matrix, Entries (some of them are located under different tabs)

**Comment by janhenckens** [comment]
Is it possible to share your database/composer @ReXTaN? Had this reported before but couldn't reproduce it at the time. (jan@studioespresso.co or through the Craft CMS Discord)

**Comment by belkin** [comment]
@janhenckens Sorry but I'm not able to send database/composer files. :/ But maybe I can make somekind of logs or check details over de fields?

**Comment by janhenckens** [comment]
@ReXTaN That's ok. Field details would be good too, then I'll try to rebuild the your field in my test install and see if I can reproduce it that way.

**Comment by jan-dh** [comment]
Still getting this error on the latest version, php7.3

**Comment by janhenckens** [comment]
Haven't gotten around to releasing this, I'll try to this week!

**Comment by janhenckens** [comment]
Update is out! Can you try again @jan-dh @ReXTaN? Thanks!
